import React from 'react'

function Demo() {
  return (
    <div className=' container-fluid'>
        <div className=' row'>
            <div style={{height:'100vh'}} className=' side-menu col-4 bg-danger'>

            </div>
            <div style={{height:'100vh', overflow:'auto'}} className=' bg-primary content col-8'>
            dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic
            dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkicdcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic dcucuicdivfdvfvufdudvfdbfufdbjkic
            </div>
        </div>
    </div>
  )
}

export default Demo